spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: rootUser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always


  cloud:
    config:
      import-check: 
        enabled: false

server:
  port: 8080
  servlet:
    context-path: /api/orders

data:
  redis:
    host: localhost
    port: 6379

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"